condense_wildcard_suffixes = true
edition = "2018"
format_code_in_doc_comments = true
format_macro_matchers = true
normalize_comments = true
overflow_delimited_expr = true
use_field_init_shorthand = true
wrap_comments = true
imports_granularity = "module"
group_imports = "StdExternalCrate"